#ifndef CAPTUREMANAGERQTPROXY_GLOBAL_H
#define CAPTUREMANAGERQTPROXY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAPTUREMANAGERQTPROXY_LIBRARY)
#  define CAPTUREMANAGERQTPROXYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAPTUREMANAGERQTPROXYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAPTUREMANAGERQTPROXY_GLOBAL_H
